# up this docker document
# docker-compose up -d
# docker-compose up --build
# docker-compose down

version: '3.6'

services:
  unip_mysql:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: unip_pwd
      MYSQL_DATABASE: DB_UNIP
    volumes:
      - unip_volume:/var/lib/mysql:rw
    networks:
      - unip_network

  unip_adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - unip_network

networks:
  unip_network:
    driver: bridge

volumes:
  unip_volume: