# docker-compose up -d
# docker-compose up --build
# docker-compose down

version: '3.6'

services:
  mysql_server:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: unip_pwd
      MYSQL_DATABASE: DB_PIM_VIII
    volumes:
      - mysql_volume:/var/lib/mysql:rw
    networks:
      - mysql_network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - mysql_network

networks:
  mysql_network:
    driver: bridge

volumes:
  mysql_volume: