// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PIM_VIII.Datas;

#nullable disable

namespace PIM_VIII.Migrations
{
    [DbContext(typeof(BancoDadosContext))]
    [Migration("20221110005501_DataContext")]
    partial class DataContext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PIM_VIII.Models.Endereco", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("bairro")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("cep")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("cidade")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("estado")
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.Property<string>("logradouro")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<int>("numero")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("TB_ENDERECOS");
                });

            modelBuilder.Entity("PIM_VIII.Models.Pessoa", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<long>("cpf")
                        .HasMaxLength(11)
                        .HasColumnType("bigint");

                    b.Property<int?>("enderecoId")
                        .HasColumnType("int");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.HasKey("id");

                    b.HasIndex("cpf")
                        .IsUnique();

                    b.HasIndex("enderecoId");

                    b.ToTable("TB_PESSOAS");
                });

            modelBuilder.Entity("PIM_VIII.Models.PessoaTelefone", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("pessoaId")
                        .HasColumnType("int");

                    b.Property<int?>("telefoneId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("pessoaId")
                        .IsUnique();

                    b.ToTable("TB_PESSOAS_TELEFONES");
                });

            modelBuilder.Entity("PIM_VIII.Models.Telefone", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("PessoaTelefoneid")
                        .HasColumnType("int");

                    b.Property<int>("ddd")
                        .HasColumnType("int");

                    b.Property<int>("numero")
                        .HasMaxLength(9)
                        .IsUnicode(true)
                        .HasColumnType("int");

                    b.Property<int?>("tipoId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("PessoaTelefoneid");

                    b.HasIndex("tipoId");

                    b.ToTable("TB_TELEFONES");
                });

            modelBuilder.Entity("PIM_VIII.Models.TipoTelefone", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("tipo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("id");

                    b.ToTable("TB_TIPOS_TELEFONES");
                });

            modelBuilder.Entity("PIM_VIII.Models.Pessoa", b =>
                {
                    b.HasOne("PIM_VIII.Models.Endereco", "endereco")
                        .WithMany()
                        .HasForeignKey("enderecoId");

                    b.Navigation("endereco");
                });

            modelBuilder.Entity("PIM_VIII.Models.PessoaTelefone", b =>
                {
                    b.HasOne("PIM_VIII.Models.Pessoa", "pessoa")
                        .WithOne()
                        .HasForeignKey("PIM_VIII.Models.PessoaTelefone", "pessoaId");

                    b.Navigation("pessoa");
                });

            modelBuilder.Entity("PIM_VIII.Models.Telefone", b =>
                {
                    b.HasOne("PIM_VIII.Models.PessoaTelefone", null)
                        .WithMany("telefones")
                        .HasForeignKey("PessoaTelefoneid");

                    b.HasOne("PIM_VIII.Models.TipoTelefone", "tipo")
                        .WithMany()
                        .HasForeignKey("tipoId");

                    b.Navigation("tipo");
                });

            modelBuilder.Entity("PIM_VIII.Models.PessoaTelefone", b =>
                {
                    b.Navigation("telefones");
                });
#pragma warning restore 612, 618
        }
    }
}
